projectPiki/pikmin

.github/workflows/build.yml, Makefile, tools/calcprogress.py
Basically a copy/paste of encounter's work for pikmin2.
Successful run: https://github.com/r-burns/pikmin/runs/5951250562
=> ci: Add GitHub action 

tools/frank.py
If an object file contains no code (e.g. files containing only data
structures, or stub files which only include their respective header),
the codesize magic will not be found. Rather than silently continuing
with an invalid code_size_offset of (-1 + 12), we should use the vanilla
bytes verbatim and exit early.
=> frank.py: Skip objects containing no code

tools/frank.py
Adds postprocessing step for lmw/lwz ordering
Pikmin repo still `OK`
=> Pull latest changes to frank.py from melee

tools/frank.py
Sync with https://github.com/doldecomp/melee/pull/929
=> Sync frank with melee

configure.py, include/Graphics.h, include/Win.h, src/plugPikiKando/gmWin.cpp, src/sysDolphin/dgxGraphics.cpp
Baby's first decomp match.  Woo hoo!
=> Matching: gmWin.cpp

configure.py, include/SoundMgr.h, include/Win.h, include/jaudio/PikiPlayer.h, include/jaudio/verysimple.h, src/jaudio/piki_player.c, src/jaudio/verysimple.c, src/plugPikiKando/seMgr.cpp
My bad for sitting on this for three days.
=> SeMgr: Matching DOL

configure.py, include/Dolphin/card.h, include/Dolphin/os.h, src/jaudio/dsp_cardunlock.c
Thank you ac-decomp for having the hard stuff already done.
=> Match jaudio/dsp_cardunlock.c

include/hvqm4.h, include/types.h, src/hvqm4dec/hvqm4dec.c
A good start to this file, as stuff inlines.
=> hvqm4dec.c: getBit | getByte | decodeHuff | HVQM4BuffSize 100%

configure.py, include/jaudio/interface.h, src/jaudio/interface.c
I don't know why this was left unfinished but okay.
=> jaudio/interface.c Matching

configure.py, src/jaudio/ja_calc.c
Heartwarming: Local decomper achieves match in 99% done file by cheating off sunshine decomp.
=> ja_calc.c: Finish Matching

include/jaudio/audiostruct.h, include/jaudio/driverinterface.h, include/jaudio/dspdriver.h, src/jaudio/driverinterface.c, src/jaudio/dspdriver.c, src/jaudio/verysimple.c
Get this one out of the backlog.  It's better than not sharing it at all.
=> driverinterface.c: Two functions lol

include/jaudio/aramcall.h, include/jaudio/heapctrl.h, src/jaudio/aramcall.c, src/jaudio/heapctrl.c, src/os/OSMessage.c
=> heapctrl.c: WIP 1

configure.py, include/jaudio/aramcall.h, include/jaudio/dummyrom.h, include/jaudio/dvdthread.h, include/jaudio/heapctrl.h, include/stl/string.h, src/MSL_C/PPCEABI/bare/H/string.c, src/jaudio/aramcall.c, src/jaudio/dummyrom.c, src/jaudio/heapctrl.c
=> aramcall.c: Equivalent

include/jaudio/audiostruct.h, include/jaudio/bankdrv.h, include/jaudio/bankread.h, include/jaudio/bx.h, include/jaudio/connect.h, include/jaudio/dspinterface.h, include/jaudio/waveread.h, src/jaudio/bankdrv.c, src/jaudio/bankread.c, src/jaudio/connect.c, src/jaudio/dspinterface.c, src/jaudio/waveread.c
idk man, I've sat on these incremental additions for long enough.
=> JAudio: Banking on Waves 

include/jaudio/jammain_2.h, include/jaudio/jamosc.h, src/jaudio/jammain_2.c, src/jaudio/jamosc.c
Starting from the smallest functions and working up.  Stopping for the night.
=> jammain_2.c: WIP

include/jaudio/pikiseq.h, include/jaudio/virload.h, src/jaudio/virload.c
I'm so bad about hoarding progress...
=> virload.c: Old news

include/jaudio/PikiPlayer.h, include/jaudio/jammain_2.h, include/jaudio/jamosc.h, include/jaudio/seqsetup.h, src/jaudio/jammain_2.c, src/jaudio/jamosc.c, src/jaudio/piki_bgm.c, src/jaudio/piki_player.c, src/jaudio/pikidemo.c, src/jaudio/seqsetup.c, src/plugPikiKando/navi.cpp
=> jammain_2.c: Checkpoint

include/jaudio/jammain_2.h, include/jaudio/oneshot.h, include/jaudio/seqsetup.h, src/jaudio/jammain_2.c, src/jaudio/oneshot.c, src/jaudio/seqsetup.c
=> jammain_2.c: Progress, Ho!

src/jaudio/waveread.c
=> IT WAS NEVER VOLATILE

include/jaudio/jammain_2.h, include/jaudio/seqsetup.h, src/jaudio/jammain_2.c, src/jaudio/noteon.c, src/jaudio/seqsetup.c
Moar `seqp_` info. `Init_Track` seems promising.
=> seqsetup.c: WIP

include/jaudio/audiostruct.h, include/jaudio/jammain_2.h, src/jaudio/jammain_2.c, src/jaudio/seqsetup.c
=> seqsetup.c: Match `Init_Track`

configure.py, include/jaudio/seqsetup.h, src/jaudio/seqsetup.c
=> seqsetup.c: Matching

include/jaudio/jammain_2.h, src/jaudio/jammain_2.c, src/jaudio/piki_player.c, src/jaudio/pikidemo.c, src/jaudio/seqsetup.c
Thank you Pikmin 2 and future JAudio for having great intel on these structure names.
=> jammain_2.c: Thievery

src/jaudio/jammain_2.c
=> `Cmd_Printf` additions

include/jaudio/jammain_2.h, src/jaudio/jammain_2.c, src/jaudio/seqsetup.c
The bytecode interpreter in this file is starting to come together.
=> jammain_2.c: WIP some more

src/jaudio/jammain_2.c
Yeah, cleanup can wait until later.
=> jammain_2.c: Match `Jam_WriteRegParam`

src/jaudio/jammain_2.c
=> jammain_2.c: Match `Cmd_PanSwSet`

include/jaudio/jammain_2.h, src/jaudio/jammain_2.c
Surprisingly simple function to match.  After matching this function, all floats in this translation unit now exist!!  Epic.
=> jammain_2.c: Match `Jam_UpdateTrackAll`

include/jaudio/bx.h, include/jaudio/jammain_2.h, src/jaudio/driverinterface.c, src/jaudio/jammain_2.c
=> jammain_2.c: `Jam_UpdateTrack` WIP

src/jaudio/jammain_2.c
Today's lesson in trusting Ghidra more: Ghidra predicted this fix but I thought it was just misinterpreting a compiler optimization.  The compiler optimization I had in mind does actually happen but is distinct from this manually-optimized technique (and more efficient lol).
=> jammain_2.c: Match `Jam_UpdateTrack`

include/jaudio/jammain_2.h, src/jaudio/jammain_2.c, src/jaudio/jamosc.c, src/jaudio/seqsetup.c
=> Jam_SeqmainNote Progress

include/jaudio/audiostruct.h, include/jaudio/bx.h, include/jaudio/jammain_2.h, src/jaudio/driverinterface.c, src/jaudio/jammain_2.c, src/jaudio/oneshot.c, src/jaudio/seqsetup.c
=> Jam_SeqmainNote 76%

include/Actor.h, src/plugPikiKando/actor.cpp
this PR implements some functions in actor.cpp. although Actor is mostly unused, the DLL carried and let me attempt to make similar/matching functions.
i also moved/added headers around in Actor.h, as well as removing some forward declarations. please let me know if i should add any back.
=> some work on actor.cpp

configure.py, include/DebugLog.h, src/plugPikiColin/gamePrefs.cpp, src/plugPikiKando/memStat.cpp, src/plugPikiNakata/nlibfunction.cpp
Plus a few unused functions gleamed from the DLL.
=> memStat.cpp: Matching for G98E01_PIKIDEMO

configure.py, include/system.h, src/jaudio/audiothread.c, src/plugPikiColin/cardutil.cpp, src/plugPikiColin/movSample.cpp, src/sysDolphin/dgxGraphics.cpp, src/sysDolphin/system.cpp
The `OSCreateThread` mistake in `System::startLoading` was kind of funny to notice.
=> system.cpp: Matching for G98E01_PIKIDEMO

include/DebugLog.h, include/MemStat.h, src/plugPikiKando/aiTransport.cpp, src/plugPikiKando/creatureStick.cpp, src/plugPikiKando/gameDemo.cpp, src/plugPikiKando/generatorCache.cpp, src/plugPikiKando/goalItem.cpp, src/plugPikiKando/memStat.cpp, src/plugPikiKando/pelletMgr.cpp, src/plugPikiKando/pikiheadItem.cpp, src/plugPikiKando/playerState.cpp, src/plugPikiKando/routeMgr.cpp, src/plugPikiKando/simpleAI.cpp, src/plugPikiKando/soundMgr.cpp, src/plugPikiKando/uteffect.cpp, src/plugPikiKando/workObject.cpp, src/plugPikiYamashita/P2DPane.cpp, src/plugPikiYamashita/P2DScreen.cpp, src/plugPikiYamashita/P2DTextBox.cpp, src/sysDolphin/sysNew.cpp
Considerably fewer of these means I could finish it in considerably less time.  Now, mail to me the results and 逝ってよし!
=> The Missing `ERROR`s

include/DebugLog.h, src/plugPikiKando/aiAction.cpp, src/plugPikiKando/aiBridge.cpp, src/plugPikiKando/aiKinoko.cpp, src/plugPikiKando/aiTransport.cpp, src/plugPikiKando/creature.cpp, src/plugPikiKando/gameCoreSection.cpp, src/plugPikiKando/generatorCache.cpp, src/plugPikiKando/goalItem.cpp, src/plugPikiKando/interactBattle.cpp, src/plugPikiKando/itemMgr.cpp, src/plugPikiKando/navi.cpp, src/plugPikiKando/naviState.cpp, src/plugPikiKando/pelletMgr.cpp, src/plugPikiKando/piki.cpp, src/plugPikiKando/playerState.cpp, src/plugPikiKando/routeMgr.cpp, src/plugPikiKando/viewPiki.cpp, src/plugPikiKando/workObject.cpp
Called `GlobalDebugPrint` in the Ghidra repo, but I don't know why.
=> The missing `PRINT_GLOBAL`s

src/jaudio/dspdriver.c
=> Fix :matchFail:
